/**
 * 网易云 API 注册表 — 439 个接口（api-enhanced 全量，零遗漏）
 * 模块按功能家族合并于 modules/<group>.ts（23 个组文件）；本文件由合并脚本生成。
 * 路由规则对齐 server.js：文件名下划线转斜杠，daily_signin / fm_trash / personal_fm 三个特殊路由原样。
 */
import type { NcmModule } from "./types";

import { activate_init_profile, captcha_safe_sent, captcha_sent, captcha_sent_v1, captcha_verify, cellphone_existence_check, countries_code_list, login, login_cellphone, login_qr_check, login_qr_create, login_qr_key, login_refresh, login_status, logout, nickname_check, rebind, register_anonimous, register_cellphone, register_checktoken_v2, register_checktoken_v3, register_xeapikey, user_binding, user_bindingcellphone, user_replacephone, verify_getQr, verify_qrcodestatus } from "./modules/account";
import { album, album_detail, album_detail_dynamic, album_list, album_list_style, album_new, album_newest, album_privilege, album_songsaleboard, album_sub, album_sublist, digitalAlbum_detail, digitalAlbum_ordering, digitalAlbum_purchased, digitalAlbum_sales } from "./modules/album";
import { artist_album, artist_desc, artist_detail, artist_detail_dynamic, artist_fans, artist_follow_count, artist_list, artist_mv, artist_new_mv, artist_new_song, artist_new_song_mv_list_v2, artist_new_song_playall, artist_songs, artist_sub, artist_sublist, artist_top_song, artist_video, artists, simi_artist } from "./modules/artist";
import { broadcast_category_region_get, broadcast_channel_collect_list, broadcast_channel_currentinfo, broadcast_channel_list, broadcast_sub } from "./modules/broadcast";
import { cloud, cloud_import, cloud_lyric_get, cloud_match, cloud_upload_complete, cloud_upload_token, voice_delete, voice_detail, voice_lyric, voice_upload, voicelist_detail, voicelist_list, voicelist_list_search, voicelist_my_created, voicelist_search, voicelist_trans } from "./modules/cloud";
import { comment, comment_add, comment_album, comment_delete, comment_dj, comment_event, comment_floor, comment_hot, comment_hug_list, comment_info_list, comment_like, comment_music, comment_mv, comment_new, comment_playlist, comment_reply, comment_report, comment_video, hug_comment } from "./modules/comment";
import { djRadio_top, dj_banner, dj_category_excludehot, dj_category_recommend, dj_catelist, dj_detail, dj_difm_all_style_channel, dj_difm_channel_subscribe, dj_difm_channel_unsubscribe, dj_difm_playing_tracks_list, dj_difm_subscribe_channels_get, dj_hot, dj_paygift, dj_personalize_recommend, dj_program, dj_program_detail, dj_program_toplist, dj_program_toplist_hours, dj_radio_hot, dj_recommend, dj_recommend_type, dj_sub, dj_sublist, dj_subscriber, dj_today_perfered, dj_toplist, dj_toplist_hours, dj_toplist_newcomer, dj_toplist_pay, dj_toplist_popular } from "./modules/dj";
import { fanscenter_basicinfo_age_get, fanscenter_basicinfo_gender_get, fanscenter_basicinfo_province_get, fanscenter_overview_get, fanscenter_trend_list } from "./modules/fanscenter";
import { fm_trash, personal_fm, personal_fm_mode } from "./modules/fm";
import { daily_signin, listen_data_realtime_report, listen_data_report, listen_data_song_play_rank, listen_data_today_song, listen_data_total, listen_data_year_report, recent_listen_list, record_recent_album, record_recent_dj, record_recent_playlist, record_recent_song, record_recent_video, record_recent_voice, sign_happy_info, signin_progress, summary_annual } from "./modules/listening";
import { listentogether_accept, listentogether_end, listentogether_heatbeat, listentogether_play_command, listentogether_room_check, listentogether_room_create, listentogether_status, listentogether_sync_list_command, listentogether_sync_playlist_get } from "./modules/listentogether";
import { ad_get, ad_listening_rights, ad_listening_rights_gain, aidj_content_rcmd, chart_detail, chart_song_detail, creator_authinfo_get, lbs_city_code, middle_play_do_lottery, middle_play_lottery_remain_chance, pl_count, program_recommend, radio_sport_get, rep_ugc_activity_collect, rep_ugc_activity_get, rep_ugc_exam_info_get, rep_ugc_exam_question_single_get, rep_ugc_exam_result_get, rep_ugc_exam_start, rep_ugc_exam_submit, rep_ugc_user_collect_vip, rep_ugc_user_get, rep_ugc_user_sign, rep_ugc_user_vip, resource_like, sati_resource_list, sati_resource_list_more, sati_resource_sub, sati_resource_sub_list, sati_tag_list, sati_timescene_resources_get, setting, sheet_list, sheet_preview, simi_playlist, simi_user, starpick_comments_summary, style_album, style_artist, style_detail, style_list, style_playlist, style_preference, style_song, thinktank_audit_resource_detail, thinktank_audit_resource_update, threshold_detail_get, topic_detail, topic_detail_event_hot, topic_sublist, ugc_album_get, ugc_artist_get, ugc_artist_search, ugc_detail, ugc_mv_get, ugc_song_get, ugc_user_devote } from "./modules/misc";
import { musician_cloudbean, musician_cloudbean_obtain, musician_data_overview, musician_play_trend, musician_sign, musician_tasks, musician_tasks_new, musician_vip_tasks } from "./modules/musician";
import { playlist_category_list, playlist_catlist, playlist_cover_update, playlist_create, playlist_delete, playlist_desc_update, playlist_detail, playlist_detail_dynamic, playlist_detail_rcmd_get, playlist_highquality_tags, playlist_hot, playlist_import_name_task_create, playlist_import_task_status, playlist_mylike, playlist_name_update, playlist_order_update, playlist_privacy, playlist_subscribe, playlist_subscribers, playlist_tags_update, playlist_track_add, playlist_track_all, playlist_track_delete, playlist_tracks, playlist_update, playlist_update_playcount, playlist_video_recent, related_playlist, top_playlist, top_playlist_highquality } from "./modules/playlist";
import { banner, calendar, history_recommend_songs, history_recommend_songs_detail, homepage_block_page, homepage_dragon_ball, hot_topic, personalized, personalized_djprogram, personalized_mv, personalized_newsong, personalized_privatecontent, personalized_privatecontent_list, recommend_resource, recommend_songs, recommend_songs_dislike, top_album, top_artists, top_list, top_mv, top_song, toplist, toplist_artist, toplist_detail, toplist_detail_v2 } from "./modules/recommend";
import { cloudsearch, search, search_default, search_hot, search_hot_detail, search_match, search_multimatch, search_suggest, search_suggest_pc } from "./modules/search";
import { event, event_del, event_forward, event_privacy, follow, msg_comments, msg_forwards, msg_notices, msg_private, msg_private_history, msg_recentcontact, send_album, send_playlist, send_song, send_text, share_resource } from "./modules/social";
import { audio_match, check_music, like, like_v1, likelist, lyric, lyric_new, music_first_listen_info, playmode_intelligence_list, playmode_song_vector, relay_play_state_submit, scrobble, scrobble_v1, simi_song, song_chorus, song_cloud_download, song_copyright_rcmd, song_creators, song_detail, song_downlist, song_download_url, song_download_url_v1, song_dynamic_cover, song_like, song_like_check, song_lyrics_mark, song_lyrics_mark_add, song_lyrics_mark_del, song_lyrics_mark_user_page, song_monthdownlist, song_music_detail, song_order_update, song_purchased, song_red_count, song_simi_get, song_singledownlist, song_url, song_url_match, song_url_ncmget, song_url_v1, song_url_v1_302, song_wiki_info, song_wiki_summary, weblog } from "./modules/song";
import { api, avatar_upload, batch, decrypt, eapi_decrypt, inner_version } from "./modules/tools";
import { device_kickoff, device_list, get_userids, user_account, user_audio, user_cloud, user_cloud_del, user_cloud_detail, user_comment_history, user_detail, user_detail_new, user_dj, user_event, user_event_all, user_follow_mixed, user_followeds, user_follows, user_level, user_medal, user_mutualfollow_get, user_playlist, user_playlist_collect, user_playlist_create, user_record, user_social_status, user_social_status_edit, user_social_status_rcmd, user_social_status_support, user_subcount, user_update } from "./modules/user";
import { mlog_music_rcmd, mlog_to_video, mlog_url, mv_all, mv_detail, mv_detail_info, mv_exclusive_rcmd, mv_first, mv_sub, mv_sublist, mv_url, related_allvideo, simi_mv, video_category_list, video_detail, video_detail_info, video_group, video_group_list, video_sub, video_timeline_all, video_timeline_recommend, video_url } from "./modules/video";
import { vip_growthpoint, vip_growthpoint_details, vip_growthpoint_get, vip_growthpoint_getall, vip_info, vip_info_v2, vip_sign, vip_sign_detail, vip_sign_history, vip_sign_info, vip_tasks, vip_tasks_v1, vip_timemachine } from "./modules/vip";
import { yunbei, yunbei_expense, yunbei_info, yunbei_rcmd_song, yunbei_rcmd_song_history, yunbei_receipt, yunbei_sign, yunbei_task_finish, yunbei_task_finish_v1, yunbei_task_list_v1, yunbei_task_recommend_song, yunbei_tasks, yunbei_tasks_todo, yunbei_today } from "./modules/yunbei";

export interface NcmModuleEntry {
  name: string;
  route: string;
  category: string;
  module: NcmModule;
}

export const MODULES: Record<string, NcmModuleEntry> = {
  "activate_init_profile": { name: "activate_init_profile", route: "/activate/init/profile", category: "登录与账号", module: activate_init_profile },
  "ad_get": { name: "ad_get", route: "/ad/get", category: "其他", module: ad_get },
  "ad_listening_rights": { name: "ad_listening_rights", route: "/ad/listening/rights", category: "其他", module: ad_listening_rights },
  "ad_listening_rights_gain": { name: "ad_listening_rights_gain", route: "/ad/listening/rights/gain", category: "其他", module: ad_listening_rights_gain },
  "aidj_content_rcmd": { name: "aidj_content_rcmd", route: "/aidj/content/rcmd", category: "其他", module: aidj_content_rcmd },
  "album": { name: "album", route: "/album", category: "专辑", module: album },
  "album_detail": { name: "album_detail", route: "/album/detail", category: "专辑", module: album_detail },
  "album_detail_dynamic": { name: "album_detail_dynamic", route: "/album/detail/dynamic", category: "专辑", module: album_detail_dynamic },
  "album_list": { name: "album_list", route: "/album/list", category: "专辑", module: album_list },
  "album_list_style": { name: "album_list_style", route: "/album/list/style", category: "专辑", module: album_list_style },
  "album_new": { name: "album_new", route: "/album/new", category: "专辑", module: album_new },
  "album_newest": { name: "album_newest", route: "/album/newest", category: "专辑", module: album_newest },
  "album_privilege": { name: "album_privilege", route: "/album/privilege", category: "专辑", module: album_privilege },
  "album_songsaleboard": { name: "album_songsaleboard", route: "/album/songsaleboard", category: "专辑", module: album_songsaleboard },
  "album_sub": { name: "album_sub", route: "/album/sub", category: "专辑", module: album_sub },
  "album_sublist": { name: "album_sublist", route: "/album/sublist", category: "专辑", module: album_sublist },
  "api": { name: "api", route: "/api", category: "工具与调试", module: api },
  "artist_album": { name: "artist_album", route: "/artist/album", category: "歌手", module: artist_album },
  "artist_desc": { name: "artist_desc", route: "/artist/desc", category: "歌手", module: artist_desc },
  "artist_detail": { name: "artist_detail", route: "/artist/detail", category: "歌手", module: artist_detail },
  "artist_detail_dynamic": { name: "artist_detail_dynamic", route: "/artist/detail/dynamic", category: "歌手", module: artist_detail_dynamic },
  "artist_fans": { name: "artist_fans", route: "/artist/fans", category: "歌手", module: artist_fans },
  "artist_follow_count": { name: "artist_follow_count", route: "/artist/follow/count", category: "歌手", module: artist_follow_count },
  "artist_list": { name: "artist_list", route: "/artist/list", category: "歌手", module: artist_list },
  "artist_mv": { name: "artist_mv", route: "/artist/mv", category: "歌手", module: artist_mv },
  "artist_new_mv": { name: "artist_new_mv", route: "/artist/new/mv", category: "歌手", module: artist_new_mv },
  "artist_new_song": { name: "artist_new_song", route: "/artist/new/song", category: "歌手", module: artist_new_song },
  "artist_new_song_mv_list_v2": { name: "artist_new_song_mv_list_v2", route: "/artist/new/song/mv/list/v2", category: "歌手", module: artist_new_song_mv_list_v2 },
  "artist_new_song_playall": { name: "artist_new_song_playall", route: "/artist/new/song/playall", category: "歌手", module: artist_new_song_playall },
  "artist_songs": { name: "artist_songs", route: "/artist/songs", category: "歌手", module: artist_songs },
  "artist_sub": { name: "artist_sub", route: "/artist/sub", category: "歌手", module: artist_sub },
  "artist_sublist": { name: "artist_sublist", route: "/artist/sublist", category: "歌手", module: artist_sublist },
  "artist_top_song": { name: "artist_top_song", route: "/artist/top/song", category: "歌手", module: artist_top_song },
  "artist_video": { name: "artist_video", route: "/artist/video", category: "歌手", module: artist_video },
  "artists": { name: "artists", route: "/artists", category: "歌手", module: artists },
  "audio_match": { name: "audio_match", route: "/audio/match", category: "歌曲", module: audio_match },
  "avatar_upload": { name: "avatar_upload", route: "/avatar/upload", category: "工具与调试", module: avatar_upload },
  "banner": { name: "banner", route: "/banner", category: "推荐与榜单", module: banner },
  "batch": { name: "batch", route: "/batch", category: "工具与调试", module: batch },
  "broadcast_category_region_get": { name: "broadcast_category_region_get", route: "/broadcast/category/region/get", category: "广播", module: broadcast_category_region_get },
  "broadcast_channel_collect_list": { name: "broadcast_channel_collect_list", route: "/broadcast/channel/collect/list", category: "广播", module: broadcast_channel_collect_list },
  "broadcast_channel_currentinfo": { name: "broadcast_channel_currentinfo", route: "/broadcast/channel/currentinfo", category: "广播", module: broadcast_channel_currentinfo },
  "broadcast_channel_list": { name: "broadcast_channel_list", route: "/broadcast/channel/list", category: "广播", module: broadcast_channel_list },
  "broadcast_sub": { name: "broadcast_sub", route: "/broadcast/sub", category: "广播", module: broadcast_sub },
  "calendar": { name: "calendar", route: "/calendar", category: "推荐与榜单", module: calendar },
  "captcha_safe_sent": { name: "captcha_safe_sent", route: "/captcha/safe/sent", category: "登录与账号", module: captcha_safe_sent },
  "captcha_sent": { name: "captcha_sent", route: "/captcha/sent", category: "登录与账号", module: captcha_sent },
  "captcha_sent_v1": { name: "captcha_sent_v1", route: "/captcha/sent/v1", category: "登录与账号", module: captcha_sent_v1 },
  "captcha_verify": { name: "captcha_verify", route: "/captcha/verify", category: "登录与账号", module: captcha_verify },
  "cellphone_existence_check": { name: "cellphone_existence_check", route: "/cellphone/existence/check", category: "登录与账号", module: cellphone_existence_check },
  "chart_detail": { name: "chart_detail", route: "/chart/detail", category: "其他", module: chart_detail },
  "chart_song_detail": { name: "chart_song_detail", route: "/chart/song/detail", category: "其他", module: chart_song_detail },
  "check_music": { name: "check_music", route: "/check/music", category: "歌曲", module: check_music },
  "cloud": { name: "cloud", route: "/cloud", category: "云盘与声音", module: cloud },
  "cloud_import": { name: "cloud_import", route: "/cloud/import", category: "云盘与声音", module: cloud_import },
  "cloud_lyric_get": { name: "cloud_lyric_get", route: "/cloud/lyric/get", category: "云盘与声音", module: cloud_lyric_get },
  "cloud_match": { name: "cloud_match", route: "/cloud/match", category: "云盘与声音", module: cloud_match },
  "cloud_upload_complete": { name: "cloud_upload_complete", route: "/cloud/upload/complete", category: "云盘与声音", module: cloud_upload_complete },
  "cloud_upload_token": { name: "cloud_upload_token", route: "/cloud/upload/token", category: "云盘与声音", module: cloud_upload_token },
  "cloudsearch": { name: "cloudsearch", route: "/cloudsearch", category: "搜索", module: cloudsearch },
  "comment": { name: "comment", route: "/comment", category: "评论", module: comment },
  "comment_add": { name: "comment_add", route: "/comment/add", category: "评论", module: comment_add },
  "comment_album": { name: "comment_album", route: "/comment/album", category: "评论", module: comment_album },
  "comment_delete": { name: "comment_delete", route: "/comment/delete", category: "评论", module: comment_delete },
  "comment_dj": { name: "comment_dj", route: "/comment/dj", category: "评论", module: comment_dj },
  "comment_event": { name: "comment_event", route: "/comment/event", category: "评论", module: comment_event },
  "comment_floor": { name: "comment_floor", route: "/comment/floor", category: "评论", module: comment_floor },
  "comment_hot": { name: "comment_hot", route: "/comment/hot", category: "评论", module: comment_hot },
  "comment_hug_list": { name: "comment_hug_list", route: "/comment/hug/list", category: "评论", module: comment_hug_list },
  "comment_info_list": { name: "comment_info_list", route: "/comment/info/list", category: "评论", module: comment_info_list },
  "comment_like": { name: "comment_like", route: "/comment/like", category: "评论", module: comment_like },
  "comment_music": { name: "comment_music", route: "/comment/music", category: "评论", module: comment_music },
  "comment_mv": { name: "comment_mv", route: "/comment/mv", category: "评论", module: comment_mv },
  "comment_new": { name: "comment_new", route: "/comment/new", category: "评论", module: comment_new },
  "comment_playlist": { name: "comment_playlist", route: "/comment/playlist", category: "评论", module: comment_playlist },
  "comment_reply": { name: "comment_reply", route: "/comment/reply", category: "评论", module: comment_reply },
  "comment_report": { name: "comment_report", route: "/comment/report", category: "评论", module: comment_report },
  "comment_video": { name: "comment_video", route: "/comment/video", category: "评论", module: comment_video },
  "countries_code_list": { name: "countries_code_list", route: "/countries/code/list", category: "登录与账号", module: countries_code_list },
  "creator_authinfo_get": { name: "creator_authinfo_get", route: "/creator/authinfo/get", category: "其他", module: creator_authinfo_get },
  "daily_signin": { name: "daily_signin", route: "/daily_signin", category: "听歌数据", module: daily_signin },
  "decrypt": { name: "decrypt", route: "/decrypt", category: "工具与调试", module: decrypt },
  "device_kickoff": { name: "device_kickoff", route: "/device/kickoff", category: "用户信息", module: device_kickoff },
  "device_list": { name: "device_list", route: "/device/list", category: "用户信息", module: device_list },
  "digitalAlbum_detail": { name: "digitalAlbum_detail", route: "/digitalAlbum/detail", category: "专辑", module: digitalAlbum_detail },
  "digitalAlbum_ordering": { name: "digitalAlbum_ordering", route: "/digitalAlbum/ordering", category: "专辑", module: digitalAlbum_ordering },
  "digitalAlbum_purchased": { name: "digitalAlbum_purchased", route: "/digitalAlbum/purchased", category: "专辑", module: digitalAlbum_purchased },
  "digitalAlbum_sales": { name: "digitalAlbum_sales", route: "/digitalAlbum/sales", category: "专辑", module: digitalAlbum_sales },
  "djRadio_top": { name: "djRadio_top", route: "/djRadio/top", category: "播客与DJ", module: djRadio_top },
  "dj_banner": { name: "dj_banner", route: "/dj/banner", category: "播客与DJ", module: dj_banner },
  "dj_category_excludehot": { name: "dj_category_excludehot", route: "/dj/category/excludehot", category: "播客与DJ", module: dj_category_excludehot },
  "dj_category_recommend": { name: "dj_category_recommend", route: "/dj/category/recommend", category: "播客与DJ", module: dj_category_recommend },
  "dj_catelist": { name: "dj_catelist", route: "/dj/catelist", category: "播客与DJ", module: dj_catelist },
  "dj_detail": { name: "dj_detail", route: "/dj/detail", category: "播客与DJ", module: dj_detail },
  "dj_difm_all_style_channel": { name: "dj_difm_all_style_channel", route: "/dj/difm/all/style/channel", category: "播客与DJ", module: dj_difm_all_style_channel },
  "dj_difm_channel_subscribe": { name: "dj_difm_channel_subscribe", route: "/dj/difm/channel/subscribe", category: "播客与DJ", module: dj_difm_channel_subscribe },
  "dj_difm_channel_unsubscribe": { name: "dj_difm_channel_unsubscribe", route: "/dj/difm/channel/unsubscribe", category: "播客与DJ", module: dj_difm_channel_unsubscribe },
  "dj_difm_playing_tracks_list": { name: "dj_difm_playing_tracks_list", route: "/dj/difm/playing/tracks/list", category: "播客与DJ", module: dj_difm_playing_tracks_list },
  "dj_difm_subscribe_channels_get": { name: "dj_difm_subscribe_channels_get", route: "/dj/difm/subscribe/channels/get", category: "播客与DJ", module: dj_difm_subscribe_channels_get },
  "dj_hot": { name: "dj_hot", route: "/dj/hot", category: "播客与DJ", module: dj_hot },
  "dj_paygift": { name: "dj_paygift", route: "/dj/paygift", category: "播客与DJ", module: dj_paygift },
  "dj_personalize_recommend": { name: "dj_personalize_recommend", route: "/dj/personalize/recommend", category: "播客与DJ", module: dj_personalize_recommend },
  "dj_program": { name: "dj_program", route: "/dj/program", category: "播客与DJ", module: dj_program },
  "dj_program_detail": { name: "dj_program_detail", route: "/dj/program/detail", category: "播客与DJ", module: dj_program_detail },
  "dj_program_toplist": { name: "dj_program_toplist", route: "/dj/program/toplist", category: "播客与DJ", module: dj_program_toplist },
  "dj_program_toplist_hours": { name: "dj_program_toplist_hours", route: "/dj/program/toplist/hours", category: "播客与DJ", module: dj_program_toplist_hours },
  "dj_radio_hot": { name: "dj_radio_hot", route: "/dj/radio/hot", category: "播客与DJ", module: dj_radio_hot },
  "dj_recommend": { name: "dj_recommend", route: "/dj/recommend", category: "播客与DJ", module: dj_recommend },
  "dj_recommend_type": { name: "dj_recommend_type", route: "/dj/recommend/type", category: "播客与DJ", module: dj_recommend_type },
  "dj_sub": { name: "dj_sub", route: "/dj/sub", category: "播客与DJ", module: dj_sub },
  "dj_sublist": { name: "dj_sublist", route: "/dj/sublist", category: "播客与DJ", module: dj_sublist },
  "dj_subscriber": { name: "dj_subscriber", route: "/dj/subscriber", category: "播客与DJ", module: dj_subscriber },
  "dj_today_perfered": { name: "dj_today_perfered", route: "/dj/today/perfered", category: "播客与DJ", module: dj_today_perfered },
  "dj_toplist": { name: "dj_toplist", route: "/dj/toplist", category: "播客与DJ", module: dj_toplist },
  "dj_toplist_hours": { name: "dj_toplist_hours", route: "/dj/toplist/hours", category: "播客与DJ", module: dj_toplist_hours },
  "dj_toplist_newcomer": { name: "dj_toplist_newcomer", route: "/dj/toplist/newcomer", category: "播客与DJ", module: dj_toplist_newcomer },
  "dj_toplist_pay": { name: "dj_toplist_pay", route: "/dj/toplist/pay", category: "播客与DJ", module: dj_toplist_pay },
  "dj_toplist_popular": { name: "dj_toplist_popular", route: "/dj/toplist/popular", category: "播客与DJ", module: dj_toplist_popular },
  "eapi_decrypt": { name: "eapi_decrypt", route: "/eapi/decrypt", category: "工具与调试", module: eapi_decrypt },
  "event": { name: "event", route: "/event", category: "动态与社交", module: event },
  "event_del": { name: "event_del", route: "/event/del", category: "动态与社交", module: event_del },
  "event_forward": { name: "event_forward", route: "/event/forward", category: "动态与社交", module: event_forward },
  "event_privacy": { name: "event_privacy", route: "/event/privacy", category: "动态与社交", module: event_privacy },
  "fanscenter_basicinfo_age_get": { name: "fanscenter_basicinfo_age_get", route: "/fanscenter/basicinfo/age/get", category: "粉丝中心", module: fanscenter_basicinfo_age_get },
  "fanscenter_basicinfo_gender_get": { name: "fanscenter_basicinfo_gender_get", route: "/fanscenter/basicinfo/gender/get", category: "粉丝中心", module: fanscenter_basicinfo_gender_get },
  "fanscenter_basicinfo_province_get": { name: "fanscenter_basicinfo_province_get", route: "/fanscenter/basicinfo/province/get", category: "粉丝中心", module: fanscenter_basicinfo_province_get },
  "fanscenter_overview_get": { name: "fanscenter_overview_get", route: "/fanscenter/overview/get", category: "粉丝中心", module: fanscenter_overview_get },
  "fanscenter_trend_list": { name: "fanscenter_trend_list", route: "/fanscenter/trend/list", category: "粉丝中心", module: fanscenter_trend_list },
  "fm_trash": { name: "fm_trash", route: "/fm_trash", category: "私人FM", module: fm_trash },
  "follow": { name: "follow", route: "/follow", category: "动态与社交", module: follow },
  "get_userids": { name: "get_userids", route: "/get/userids", category: "用户信息", module: get_userids },
  "history_recommend_songs": { name: "history_recommend_songs", route: "/history/recommend/songs", category: "推荐与榜单", module: history_recommend_songs },
  "history_recommend_songs_detail": { name: "history_recommend_songs_detail", route: "/history/recommend/songs/detail", category: "推荐与榜单", module: history_recommend_songs_detail },
  "homepage_block_page": { name: "homepage_block_page", route: "/homepage/block/page", category: "推荐与榜单", module: homepage_block_page },
  "homepage_dragon_ball": { name: "homepage_dragon_ball", route: "/homepage/dragon/ball", category: "推荐与榜单", module: homepage_dragon_ball },
  "hot_topic": { name: "hot_topic", route: "/hot/topic", category: "推荐与榜单", module: hot_topic },
  "hug_comment": { name: "hug_comment", route: "/hug/comment", category: "评论", module: hug_comment },
  "inner_version": { name: "inner_version", route: "/inner/version", category: "工具与调试", module: inner_version },
  "lbs_city_code": { name: "lbs_city_code", route: "/lbs/city/code", category: "其他", module: lbs_city_code },
  "like": { name: "like", route: "/like", category: "歌曲", module: like },
  "like_v1": { name: "like_v1", route: "/like/v1", category: "歌曲", module: like_v1 },
  "likelist": { name: "likelist", route: "/likelist", category: "歌曲", module: likelist },
  "listen_data_realtime_report": { name: "listen_data_realtime_report", route: "/listen/data/realtime/report", category: "听歌数据", module: listen_data_realtime_report },
  "listen_data_report": { name: "listen_data_report", route: "/listen/data/report", category: "听歌数据", module: listen_data_report },
  "listen_data_song_play_rank": { name: "listen_data_song_play_rank", route: "/listen/data/song/play/rank", category: "听歌数据", module: listen_data_song_play_rank },
  "listen_data_today_song": { name: "listen_data_today_song", route: "/listen/data/today/song", category: "听歌数据", module: listen_data_today_song },
  "listen_data_total": { name: "listen_data_total", route: "/listen/data/total", category: "听歌数据", module: listen_data_total },
  "listen_data_year_report": { name: "listen_data_year_report", route: "/listen/data/year/report", category: "听歌数据", module: listen_data_year_report },
  "listentogether_accept": { name: "listentogether_accept", route: "/listentogether/accept", category: "一起听", module: listentogether_accept },
  "listentogether_end": { name: "listentogether_end", route: "/listentogether/end", category: "一起听", module: listentogether_end },
  "listentogether_heatbeat": { name: "listentogether_heatbeat", route: "/listentogether/heatbeat", category: "一起听", module: listentogether_heatbeat },
  "listentogether_play_command": { name: "listentogether_play_command", route: "/listentogether/play/command", category: "一起听", module: listentogether_play_command },
  "listentogether_room_check": { name: "listentogether_room_check", route: "/listentogether/room/check", category: "一起听", module: listentogether_room_check },
  "listentogether_room_create": { name: "listentogether_room_create", route: "/listentogether/room/create", category: "一起听", module: listentogether_room_create },
  "listentogether_status": { name: "listentogether_status", route: "/listentogether/status", category: "一起听", module: listentogether_status },
  "listentogether_sync_list_command": { name: "listentogether_sync_list_command", route: "/listentogether/sync/list/command", category: "一起听", module: listentogether_sync_list_command },
  "listentogether_sync_playlist_get": { name: "listentogether_sync_playlist_get", route: "/listentogether/sync/playlist/get", category: "一起听", module: listentogether_sync_playlist_get },
  "login": { name: "login", route: "/login", category: "登录与账号", module: login },
  "login_cellphone": { name: "login_cellphone", route: "/login/cellphone", category: "登录与账号", module: login_cellphone },
  "login_qr_check": { name: "login_qr_check", route: "/login/qr/check", category: "登录与账号", module: login_qr_check },
  "login_qr_create": { name: "login_qr_create", route: "/login/qr/create", category: "登录与账号", module: login_qr_create },
  "login_qr_key": { name: "login_qr_key", route: "/login/qr/key", category: "登录与账号", module: login_qr_key },
  "login_refresh": { name: "login_refresh", route: "/login/refresh", category: "登录与账号", module: login_refresh },
  "login_status": { name: "login_status", route: "/login/status", category: "登录与账号", module: login_status },
  "logout": { name: "logout", route: "/logout", category: "登录与账号", module: logout },
  "lyric": { name: "lyric", route: "/lyric", category: "歌曲", module: lyric },
  "lyric_new": { name: "lyric_new", route: "/lyric/new", category: "歌曲", module: lyric_new },
  "middle_play_do_lottery": { name: "middle_play_do_lottery", route: "/middle/play/do/lottery", category: "其他", module: middle_play_do_lottery },
  "middle_play_lottery_remain_chance": { name: "middle_play_lottery_remain_chance", route: "/middle/play/lottery/remain/chance", category: "其他", module: middle_play_lottery_remain_chance },
  "mlog_music_rcmd": { name: "mlog_music_rcmd", route: "/mlog/music/rcmd", category: "MV与视频", module: mlog_music_rcmd },
  "mlog_to_video": { name: "mlog_to_video", route: "/mlog/to/video", category: "MV与视频", module: mlog_to_video },
  "mlog_url": { name: "mlog_url", route: "/mlog/url", category: "MV与视频", module: mlog_url },
  "msg_comments": { name: "msg_comments", route: "/msg/comments", category: "动态与社交", module: msg_comments },
  "msg_forwards": { name: "msg_forwards", route: "/msg/forwards", category: "动态与社交", module: msg_forwards },
  "msg_notices": { name: "msg_notices", route: "/msg/notices", category: "动态与社交", module: msg_notices },
  "msg_private": { name: "msg_private", route: "/msg/private", category: "动态与社交", module: msg_private },
  "msg_private_history": { name: "msg_private_history", route: "/msg/private/history", category: "动态与社交", module: msg_private_history },
  "msg_recentcontact": { name: "msg_recentcontact", route: "/msg/recentcontact", category: "动态与社交", module: msg_recentcontact },
  "music_first_listen_info": { name: "music_first_listen_info", route: "/music/first/listen/info", category: "歌曲", module: music_first_listen_info },
  "musician_cloudbean": { name: "musician_cloudbean", route: "/musician/cloudbean", category: "音乐人", module: musician_cloudbean },
  "musician_cloudbean_obtain": { name: "musician_cloudbean_obtain", route: "/musician/cloudbean/obtain", category: "音乐人", module: musician_cloudbean_obtain },
  "musician_data_overview": { name: "musician_data_overview", route: "/musician/data/overview", category: "音乐人", module: musician_data_overview },
  "musician_play_trend": { name: "musician_play_trend", route: "/musician/play/trend", category: "音乐人", module: musician_play_trend },
  "musician_sign": { name: "musician_sign", route: "/musician/sign", category: "音乐人", module: musician_sign },
  "musician_tasks": { name: "musician_tasks", route: "/musician/tasks", category: "音乐人", module: musician_tasks },
  "musician_tasks_new": { name: "musician_tasks_new", route: "/musician/tasks/new", category: "音乐人", module: musician_tasks_new },
  "musician_vip_tasks": { name: "musician_vip_tasks", route: "/musician/vip/tasks", category: "音乐人", module: musician_vip_tasks },
  "mv_all": { name: "mv_all", route: "/mv/all", category: "MV与视频", module: mv_all },
  "mv_detail": { name: "mv_detail", route: "/mv/detail", category: "MV与视频", module: mv_detail },
  "mv_detail_info": { name: "mv_detail_info", route: "/mv/detail/info", category: "MV与视频", module: mv_detail_info },
  "mv_exclusive_rcmd": { name: "mv_exclusive_rcmd", route: "/mv/exclusive/rcmd", category: "MV与视频", module: mv_exclusive_rcmd },
  "mv_first": { name: "mv_first", route: "/mv/first", category: "MV与视频", module: mv_first },
  "mv_sub": { name: "mv_sub", route: "/mv/sub", category: "MV与视频", module: mv_sub },
  "mv_sublist": { name: "mv_sublist", route: "/mv/sublist", category: "MV与视频", module: mv_sublist },
  "mv_url": { name: "mv_url", route: "/mv/url", category: "MV与视频", module: mv_url },
  "nickname_check": { name: "nickname_check", route: "/nickname/check", category: "登录与账号", module: nickname_check },
  "personal_fm": { name: "personal_fm", route: "/personal_fm", category: "私人FM", module: personal_fm },
  "personal_fm_mode": { name: "personal_fm_mode", route: "/personal/fm/mode", category: "私人FM", module: personal_fm_mode },
  "personalized": { name: "personalized", route: "/personalized", category: "推荐与榜单", module: personalized },
  "personalized_djprogram": { name: "personalized_djprogram", route: "/personalized/djprogram", category: "推荐与榜单", module: personalized_djprogram },
  "personalized_mv": { name: "personalized_mv", route: "/personalized/mv", category: "推荐与榜单", module: personalized_mv },
  "personalized_newsong": { name: "personalized_newsong", route: "/personalized/newsong", category: "推荐与榜单", module: personalized_newsong },
  "personalized_privatecontent": { name: "personalized_privatecontent", route: "/personalized/privatecontent", category: "推荐与榜单", module: personalized_privatecontent },
  "personalized_privatecontent_list": { name: "personalized_privatecontent_list", route: "/personalized/privatecontent/list", category: "推荐与榜单", module: personalized_privatecontent_list },
  "pl_count": { name: "pl_count", route: "/pl/count", category: "其他", module: pl_count },
  "playlist_category_list": { name: "playlist_category_list", route: "/playlist/category/list", category: "歌单", module: playlist_category_list },
  "playlist_catlist": { name: "playlist_catlist", route: "/playlist/catlist", category: "歌单", module: playlist_catlist },
  "playlist_cover_update": { name: "playlist_cover_update", route: "/playlist/cover/update", category: "歌单", module: playlist_cover_update },
  "playlist_create": { name: "playlist_create", route: "/playlist/create", category: "歌单", module: playlist_create },
  "playlist_delete": { name: "playlist_delete", route: "/playlist/delete", category: "歌单", module: playlist_delete },
  "playlist_desc_update": { name: "playlist_desc_update", route: "/playlist/desc/update", category: "歌单", module: playlist_desc_update },
  "playlist_detail": { name: "playlist_detail", route: "/playlist/detail", category: "歌单", module: playlist_detail },
  "playlist_detail_dynamic": { name: "playlist_detail_dynamic", route: "/playlist/detail/dynamic", category: "歌单", module: playlist_detail_dynamic },
  "playlist_detail_rcmd_get": { name: "playlist_detail_rcmd_get", route: "/playlist/detail/rcmd/get", category: "歌单", module: playlist_detail_rcmd_get },
  "playlist_highquality_tags": { name: "playlist_highquality_tags", route: "/playlist/highquality/tags", category: "歌单", module: playlist_highquality_tags },
  "playlist_hot": { name: "playlist_hot", route: "/playlist/hot", category: "歌单", module: playlist_hot },
  "playlist_import_name_task_create": { name: "playlist_import_name_task_create", route: "/playlist/import/name/task/create", category: "歌单", module: playlist_import_name_task_create },
  "playlist_import_task_status": { name: "playlist_import_task_status", route: "/playlist/import/task/status", category: "歌单", module: playlist_import_task_status },
  "playlist_mylike": { name: "playlist_mylike", route: "/playlist/mylike", category: "歌单", module: playlist_mylike },
  "playlist_name_update": { name: "playlist_name_update", route: "/playlist/name/update", category: "歌单", module: playlist_name_update },
  "playlist_order_update": { name: "playlist_order_update", route: "/playlist/order/update", category: "歌单", module: playlist_order_update },
  "playlist_privacy": { name: "playlist_privacy", route: "/playlist/privacy", category: "歌单", module: playlist_privacy },
  "playlist_subscribe": { name: "playlist_subscribe", route: "/playlist/subscribe", category: "歌单", module: playlist_subscribe },
  "playlist_subscribers": { name: "playlist_subscribers", route: "/playlist/subscribers", category: "歌单", module: playlist_subscribers },
  "playlist_tags_update": { name: "playlist_tags_update", route: "/playlist/tags/update", category: "歌单", module: playlist_tags_update },
  "playlist_track_add": { name: "playlist_track_add", route: "/playlist/track/add", category: "歌单", module: playlist_track_add },
  "playlist_track_all": { name: "playlist_track_all", route: "/playlist/track/all", category: "歌单", module: playlist_track_all },
  "playlist_track_delete": { name: "playlist_track_delete", route: "/playlist/track/delete", category: "歌单", module: playlist_track_delete },
  "playlist_tracks": { name: "playlist_tracks", route: "/playlist/tracks", category: "歌单", module: playlist_tracks },
  "playlist_update": { name: "playlist_update", route: "/playlist/update", category: "歌单", module: playlist_update },
  "playlist_update_playcount": { name: "playlist_update_playcount", route: "/playlist/update/playcount", category: "歌单", module: playlist_update_playcount },
  "playlist_video_recent": { name: "playlist_video_recent", route: "/playlist/video/recent", category: "歌单", module: playlist_video_recent },
  "playmode_intelligence_list": { name: "playmode_intelligence_list", route: "/playmode/intelligence/list", category: "歌曲", module: playmode_intelligence_list },
  "playmode_song_vector": { name: "playmode_song_vector", route: "/playmode/song/vector", category: "歌曲", module: playmode_song_vector },
  "program_recommend": { name: "program_recommend", route: "/program/recommend", category: "其他", module: program_recommend },
  "radio_sport_get": { name: "radio_sport_get", route: "/radio/sport/get", category: "其他", module: radio_sport_get },
  "rebind": { name: "rebind", route: "/rebind", category: "登录与账号", module: rebind },
  "recent_listen_list": { name: "recent_listen_list", route: "/recent/listen/list", category: "听歌数据", module: recent_listen_list },
  "recommend_resource": { name: "recommend_resource", route: "/recommend/resource", category: "推荐与榜单", module: recommend_resource },
  "recommend_songs": { name: "recommend_songs", route: "/recommend/songs", category: "推荐与榜单", module: recommend_songs },
  "recommend_songs_dislike": { name: "recommend_songs_dislike", route: "/recommend/songs/dislike", category: "推荐与榜单", module: recommend_songs_dislike },
  "record_recent_album": { name: "record_recent_album", route: "/record/recent/album", category: "听歌数据", module: record_recent_album },
  "record_recent_dj": { name: "record_recent_dj", route: "/record/recent/dj", category: "听歌数据", module: record_recent_dj },
  "record_recent_playlist": { name: "record_recent_playlist", route: "/record/recent/playlist", category: "听歌数据", module: record_recent_playlist },
  "record_recent_song": { name: "record_recent_song", route: "/record/recent/song", category: "听歌数据", module: record_recent_song },
  "record_recent_video": { name: "record_recent_video", route: "/record/recent/video", category: "听歌数据", module: record_recent_video },
  "record_recent_voice": { name: "record_recent_voice", route: "/record/recent/voice", category: "听歌数据", module: record_recent_voice },
  "register_anonimous": { name: "register_anonimous", route: "/register/anonimous", category: "登录与账号", module: register_anonimous },
  "register_cellphone": { name: "register_cellphone", route: "/register/cellphone", category: "登录与账号", module: register_cellphone },
  "register_checktoken_v2": { name: "register_checktoken_v2", route: "/register/checktoken/v2", category: "登录与账号", module: register_checktoken_v2 },
  "register_checktoken_v3": { name: "register_checktoken_v3", route: "/register/checktoken/v3", category: "登录与账号", module: register_checktoken_v3 },
  "register_xeapikey": { name: "register_xeapikey", route: "/register/xeapikey", category: "登录与账号", module: register_xeapikey },
  "related_allvideo": { name: "related_allvideo", route: "/related/allvideo", category: "MV与视频", module: related_allvideo },
  "related_playlist": { name: "related_playlist", route: "/related/playlist", category: "歌单", module: related_playlist },
  "relay_play_state_submit": { name: "relay_play_state_submit", route: "/relay/play/state/submit", category: "歌曲", module: relay_play_state_submit },
  "rep_ugc_activity_collect": { name: "rep_ugc_activity_collect", route: "/rep/ugc/activity/collect", category: "其他", module: rep_ugc_activity_collect },
  "rep_ugc_activity_get": { name: "rep_ugc_activity_get", route: "/rep/ugc/activity/get", category: "其他", module: rep_ugc_activity_get },
  "rep_ugc_exam_info_get": { name: "rep_ugc_exam_info_get", route: "/rep/ugc/exam/info/get", category: "其他", module: rep_ugc_exam_info_get },
  "rep_ugc_exam_question_single_get": { name: "rep_ugc_exam_question_single_get", route: "/rep/ugc/exam/question/single/get", category: "其他", module: rep_ugc_exam_question_single_get },
  "rep_ugc_exam_result_get": { name: "rep_ugc_exam_result_get", route: "/rep/ugc/exam/result/get", category: "其他", module: rep_ugc_exam_result_get },
  "rep_ugc_exam_start": { name: "rep_ugc_exam_start", route: "/rep/ugc/exam/start", category: "其他", module: rep_ugc_exam_start },
  "rep_ugc_exam_submit": { name: "rep_ugc_exam_submit", route: "/rep/ugc/exam/submit", category: "其他", module: rep_ugc_exam_submit },
  "rep_ugc_user_collect-vip": { name: "rep_ugc_user_collect-vip", route: "/rep/ugc/user/collect-vip", category: "其他", module: rep_ugc_user_collect_vip },
  "rep_ugc_user_get": { name: "rep_ugc_user_get", route: "/rep/ugc/user/get", category: "其他", module: rep_ugc_user_get },
  "rep_ugc_user_sign": { name: "rep_ugc_user_sign", route: "/rep/ugc/user/sign", category: "其他", module: rep_ugc_user_sign },
  "rep_ugc_user_vip": { name: "rep_ugc_user_vip", route: "/rep/ugc/user/vip", category: "其他", module: rep_ugc_user_vip },
  "resource_like": { name: "resource_like", route: "/resource/like", category: "其他", module: resource_like },
  "sati_resource_list": { name: "sati_resource_list", route: "/sati/resource/list", category: "其他", module: sati_resource_list },
  "sati_resource_list_more": { name: "sati_resource_list_more", route: "/sati/resource/list/more", category: "其他", module: sati_resource_list_more },
  "sati_resource_sub": { name: "sati_resource_sub", route: "/sati/resource/sub", category: "其他", module: sati_resource_sub },
  "sati_resource_sub_list": { name: "sati_resource_sub_list", route: "/sati/resource/sub/list", category: "其他", module: sati_resource_sub_list },
  "sati_tag_list": { name: "sati_tag_list", route: "/sati/tag/list", category: "其他", module: sati_tag_list },
  "sati_timescene_resources_get": { name: "sati_timescene_resources_get", route: "/sati/timescene/resources/get", category: "其他", module: sati_timescene_resources_get },
  "scrobble": { name: "scrobble", route: "/scrobble", category: "歌曲", module: scrobble },
  "scrobble_v1": { name: "scrobble_v1", route: "/scrobble/v1", category: "歌曲", module: scrobble_v1 },
  "search": { name: "search", route: "/search", category: "搜索", module: search },
  "search_default": { name: "search_default", route: "/search/default", category: "搜索", module: search_default },
  "search_hot": { name: "search_hot", route: "/search/hot", category: "搜索", module: search_hot },
  "search_hot_detail": { name: "search_hot_detail", route: "/search/hot/detail", category: "搜索", module: search_hot_detail },
  "search_match": { name: "search_match", route: "/search/match", category: "搜索", module: search_match },
  "search_multimatch": { name: "search_multimatch", route: "/search/multimatch", category: "搜索", module: search_multimatch },
  "search_suggest": { name: "search_suggest", route: "/search/suggest", category: "搜索", module: search_suggest },
  "search_suggest_pc": { name: "search_suggest_pc", route: "/search/suggest/pc", category: "搜索", module: search_suggest_pc },
  "send_album": { name: "send_album", route: "/send/album", category: "动态与社交", module: send_album },
  "send_playlist": { name: "send_playlist", route: "/send/playlist", category: "动态与社交", module: send_playlist },
  "send_song": { name: "send_song", route: "/send/song", category: "动态与社交", module: send_song },
  "send_text": { name: "send_text", route: "/send/text", category: "动态与社交", module: send_text },
  "setting": { name: "setting", route: "/setting", category: "其他", module: setting },
  "share_resource": { name: "share_resource", route: "/share/resource", category: "动态与社交", module: share_resource },
  "sheet_list": { name: "sheet_list", route: "/sheet/list", category: "其他", module: sheet_list },
  "sheet_preview": { name: "sheet_preview", route: "/sheet/preview", category: "其他", module: sheet_preview },
  "sign_happy_info": { name: "sign_happy_info", route: "/sign/happy/info", category: "听歌数据", module: sign_happy_info },
  "signin_progress": { name: "signin_progress", route: "/signin/progress", category: "听歌数据", module: signin_progress },
  "simi_artist": { name: "simi_artist", route: "/simi/artist", category: "歌手", module: simi_artist },
  "simi_mv": { name: "simi_mv", route: "/simi/mv", category: "MV与视频", module: simi_mv },
  "simi_playlist": { name: "simi_playlist", route: "/simi/playlist", category: "其他", module: simi_playlist },
  "simi_song": { name: "simi_song", route: "/simi/song", category: "歌曲", module: simi_song },
  "simi_user": { name: "simi_user", route: "/simi/user", category: "其他", module: simi_user },
  "song_chorus": { name: "song_chorus", route: "/song/chorus", category: "歌曲", module: song_chorus },
  "song_cloud_download": { name: "song_cloud_download", route: "/song/cloud/download", category: "歌曲", module: song_cloud_download },
  "song_copyright_rcmd": { name: "song_copyright_rcmd", route: "/song/copyright/rcmd", category: "歌曲", module: song_copyright_rcmd },
  "song_creators": { name: "song_creators", route: "/song/creators", category: "歌曲", module: song_creators },
  "song_detail": { name: "song_detail", route: "/song/detail", category: "歌曲", module: song_detail },
  "song_downlist": { name: "song_downlist", route: "/song/downlist", category: "歌曲", module: song_downlist },
  "song_download_url": { name: "song_download_url", route: "/song/download/url", category: "歌曲", module: song_download_url },
  "song_download_url_v1": { name: "song_download_url_v1", route: "/song/download/url/v1", category: "歌曲", module: song_download_url_v1 },
  "song_dynamic_cover": { name: "song_dynamic_cover", route: "/song/dynamic/cover", category: "歌曲", module: song_dynamic_cover },
  "song_like": { name: "song_like", route: "/song/like", category: "歌曲", module: song_like },
  "song_like_check": { name: "song_like_check", route: "/song/like/check", category: "歌曲", module: song_like_check },
  "song_lyrics_mark": { name: "song_lyrics_mark", route: "/song/lyrics/mark", category: "歌曲", module: song_lyrics_mark },
  "song_lyrics_mark_add": { name: "song_lyrics_mark_add", route: "/song/lyrics/mark/add", category: "歌曲", module: song_lyrics_mark_add },
  "song_lyrics_mark_del": { name: "song_lyrics_mark_del", route: "/song/lyrics/mark/del", category: "歌曲", module: song_lyrics_mark_del },
  "song_lyrics_mark_user_page": { name: "song_lyrics_mark_user_page", route: "/song/lyrics/mark/user/page", category: "歌曲", module: song_lyrics_mark_user_page },
  "song_monthdownlist": { name: "song_monthdownlist", route: "/song/monthdownlist", category: "歌曲", module: song_monthdownlist },
  "song_music_detail": { name: "song_music_detail", route: "/song/music/detail", category: "歌曲", module: song_music_detail },
  "song_order_update": { name: "song_order_update", route: "/song/order/update", category: "歌曲", module: song_order_update },
  "song_purchased": { name: "song_purchased", route: "/song/purchased", category: "歌曲", module: song_purchased },
  "song_red_count": { name: "song_red_count", route: "/song/red/count", category: "歌曲", module: song_red_count },
  "song_simi_get": { name: "song_simi_get", route: "/song/simi/get", category: "歌曲", module: song_simi_get },
  "song_singledownlist": { name: "song_singledownlist", route: "/song/singledownlist", category: "歌曲", module: song_singledownlist },
  "song_url": { name: "song_url", route: "/song/url", category: "歌曲", module: song_url },
  "song_url_match": { name: "song_url_match", route: "/song/url/match", category: "歌曲", module: song_url_match },
  "song_url_ncmget": { name: "song_url_ncmget", route: "/song/url/ncmget", category: "歌曲", module: song_url_ncmget },
  "song_url_v1": { name: "song_url_v1", route: "/song/url/v1", category: "歌曲", module: song_url_v1 },
  "song_url_v1_302": { name: "song_url_v1_302", route: "/song/url/v1/302", category: "歌曲", module: song_url_v1_302 },
  "song_wiki_info": { name: "song_wiki_info", route: "/song/wiki/info", category: "歌曲", module: song_wiki_info },
  "song_wiki_summary": { name: "song_wiki_summary", route: "/song/wiki/summary", category: "歌曲", module: song_wiki_summary },
  "starpick_comments_summary": { name: "starpick_comments_summary", route: "/starpick/comments/summary", category: "其他", module: starpick_comments_summary },
  "style_album": { name: "style_album", route: "/style/album", category: "其他", module: style_album },
  "style_artist": { name: "style_artist", route: "/style/artist", category: "其他", module: style_artist },
  "style_detail": { name: "style_detail", route: "/style/detail", category: "其他", module: style_detail },
  "style_list": { name: "style_list", route: "/style/list", category: "其他", module: style_list },
  "style_playlist": { name: "style_playlist", route: "/style/playlist", category: "其他", module: style_playlist },
  "style_preference": { name: "style_preference", route: "/style/preference", category: "其他", module: style_preference },
  "style_song": { name: "style_song", route: "/style/song", category: "其他", module: style_song },
  "summary_annual": { name: "summary_annual", route: "/summary/annual", category: "听歌数据", module: summary_annual },
  "thinktank_audit_resource_detail": { name: "thinktank_audit_resource_detail", route: "/thinktank/audit/resource/detail", category: "其他", module: thinktank_audit_resource_detail },
  "thinktank_audit_resource_update": { name: "thinktank_audit_resource_update", route: "/thinktank/audit/resource/update", category: "其他", module: thinktank_audit_resource_update },
  "threshold_detail_get": { name: "threshold_detail_get", route: "/threshold/detail/get", category: "其他", module: threshold_detail_get },
  "top_album": { name: "top_album", route: "/top/album", category: "推荐与榜单", module: top_album },
  "top_artists": { name: "top_artists", route: "/top/artists", category: "推荐与榜单", module: top_artists },
  "top_list": { name: "top_list", route: "/top/list", category: "推荐与榜单", module: top_list },
  "top_mv": { name: "top_mv", route: "/top/mv", category: "推荐与榜单", module: top_mv },
  "top_playlist": { name: "top_playlist", route: "/top/playlist", category: "歌单", module: top_playlist },
  "top_playlist_highquality": { name: "top_playlist_highquality", route: "/top/playlist/highquality", category: "歌单", module: top_playlist_highquality },
  "top_song": { name: "top_song", route: "/top/song", category: "推荐与榜单", module: top_song },
  "topic_detail": { name: "topic_detail", route: "/topic/detail", category: "其他", module: topic_detail },
  "topic_detail_event_hot": { name: "topic_detail_event_hot", route: "/topic/detail/event/hot", category: "其他", module: topic_detail_event_hot },
  "topic_sublist": { name: "topic_sublist", route: "/topic/sublist", category: "其他", module: topic_sublist },
  "toplist": { name: "toplist", route: "/toplist", category: "推荐与榜单", module: toplist },
  "toplist_artist": { name: "toplist_artist", route: "/toplist/artist", category: "推荐与榜单", module: toplist_artist },
  "toplist_detail": { name: "toplist_detail", route: "/toplist/detail", category: "推荐与榜单", module: toplist_detail },
  "toplist_detail_v2": { name: "toplist_detail_v2", route: "/toplist/detail/v2", category: "推荐与榜单", module: toplist_detail_v2 },
  "ugc_album_get": { name: "ugc_album_get", route: "/ugc/album/get", category: "其他", module: ugc_album_get },
  "ugc_artist_get": { name: "ugc_artist_get", route: "/ugc/artist/get", category: "其他", module: ugc_artist_get },
  "ugc_artist_search": { name: "ugc_artist_search", route: "/ugc/artist/search", category: "其他", module: ugc_artist_search },
  "ugc_detail": { name: "ugc_detail", route: "/ugc/detail", category: "其他", module: ugc_detail },
  "ugc_mv_get": { name: "ugc_mv_get", route: "/ugc/mv/get", category: "其他", module: ugc_mv_get },
  "ugc_song_get": { name: "ugc_song_get", route: "/ugc/song/get", category: "其他", module: ugc_song_get },
  "ugc_user_devote": { name: "ugc_user_devote", route: "/ugc/user/devote", category: "其他", module: ugc_user_devote },
  "user_account": { name: "user_account", route: "/user/account", category: "用户信息", module: user_account },
  "user_audio": { name: "user_audio", route: "/user/audio", category: "用户信息", module: user_audio },
  "user_binding": { name: "user_binding", route: "/user/binding", category: "登录与账号", module: user_binding },
  "user_bindingcellphone": { name: "user_bindingcellphone", route: "/user/bindingcellphone", category: "登录与账号", module: user_bindingcellphone },
  "user_cloud": { name: "user_cloud", route: "/user/cloud", category: "用户信息", module: user_cloud },
  "user_cloud_del": { name: "user_cloud_del", route: "/user/cloud/del", category: "用户信息", module: user_cloud_del },
  "user_cloud_detail": { name: "user_cloud_detail", route: "/user/cloud/detail", category: "用户信息", module: user_cloud_detail },
  "user_comment_history": { name: "user_comment_history", route: "/user/comment/history", category: "用户信息", module: user_comment_history },
  "user_detail": { name: "user_detail", route: "/user/detail", category: "用户信息", module: user_detail },
  "user_detail_new": { name: "user_detail_new", route: "/user/detail/new", category: "用户信息", module: user_detail_new },
  "user_dj": { name: "user_dj", route: "/user/dj", category: "用户信息", module: user_dj },
  "user_event": { name: "user_event", route: "/user/event", category: "用户信息", module: user_event },
  "user_event_all": { name: "user_event_all", route: "/user/event/all", category: "用户信息", module: user_event_all },
  "user_follow_mixed": { name: "user_follow_mixed", route: "/user/follow/mixed", category: "用户信息", module: user_follow_mixed },
  "user_followeds": { name: "user_followeds", route: "/user/followeds", category: "用户信息", module: user_followeds },
  "user_follows": { name: "user_follows", route: "/user/follows", category: "用户信息", module: user_follows },
  "user_level": { name: "user_level", route: "/user/level", category: "用户信息", module: user_level },
  "user_medal": { name: "user_medal", route: "/user/medal", category: "用户信息", module: user_medal },
  "user_mutualfollow_get": { name: "user_mutualfollow_get", route: "/user/mutualfollow/get", category: "用户信息", module: user_mutualfollow_get },
  "user_playlist": { name: "user_playlist", route: "/user/playlist", category: "用户信息", module: user_playlist },
  "user_playlist_collect": { name: "user_playlist_collect", route: "/user/playlist/collect", category: "用户信息", module: user_playlist_collect },
  "user_playlist_create": { name: "user_playlist_create", route: "/user/playlist/create", category: "用户信息", module: user_playlist_create },
  "user_record": { name: "user_record", route: "/user/record", category: "用户信息", module: user_record },
  "user_replacephone": { name: "user_replacephone", route: "/user/replacephone", category: "登录与账号", module: user_replacephone },
  "user_social_status": { name: "user_social_status", route: "/user/social/status", category: "用户信息", module: user_social_status },
  "user_social_status_edit": { name: "user_social_status_edit", route: "/user/social/status/edit", category: "用户信息", module: user_social_status_edit },
  "user_social_status_rcmd": { name: "user_social_status_rcmd", route: "/user/social/status/rcmd", category: "用户信息", module: user_social_status_rcmd },
  "user_social_status_support": { name: "user_social_status_support", route: "/user/social/status/support", category: "用户信息", module: user_social_status_support },
  "user_subcount": { name: "user_subcount", route: "/user/subcount", category: "用户信息", module: user_subcount },
  "user_update": { name: "user_update", route: "/user/update", category: "用户信息", module: user_update },
  "verify_getQr": { name: "verify_getQr", route: "/verify/getQr", category: "登录与账号", module: verify_getQr },
  "verify_qrcodestatus": { name: "verify_qrcodestatus", route: "/verify/qrcodestatus", category: "登录与账号", module: verify_qrcodestatus },
  "video_category_list": { name: "video_category_list", route: "/video/category/list", category: "MV与视频", module: video_category_list },
  "video_detail": { name: "video_detail", route: "/video/detail", category: "MV与视频", module: video_detail },
  "video_detail_info": { name: "video_detail_info", route: "/video/detail/info", category: "MV与视频", module: video_detail_info },
  "video_group": { name: "video_group", route: "/video/group", category: "MV与视频", module: video_group },
  "video_group_list": { name: "video_group_list", route: "/video/group/list", category: "MV与视频", module: video_group_list },
  "video_sub": { name: "video_sub", route: "/video/sub", category: "MV与视频", module: video_sub },
  "video_timeline_all": { name: "video_timeline_all", route: "/video/timeline/all", category: "MV与视频", module: video_timeline_all },
  "video_timeline_recommend": { name: "video_timeline_recommend", route: "/video/timeline/recommend", category: "MV与视频", module: video_timeline_recommend },
  "video_url": { name: "video_url", route: "/video/url", category: "MV与视频", module: video_url },
  "vip_growthpoint": { name: "vip_growthpoint", route: "/vip/growthpoint", category: "VIP中心", module: vip_growthpoint },
  "vip_growthpoint_details": { name: "vip_growthpoint_details", route: "/vip/growthpoint/details", category: "VIP中心", module: vip_growthpoint_details },
  "vip_growthpoint_get": { name: "vip_growthpoint_get", route: "/vip/growthpoint/get", category: "VIP中心", module: vip_growthpoint_get },
  "vip_growthpoint_getall": { name: "vip_growthpoint_getall", route: "/vip/growthpoint/getall", category: "VIP中心", module: vip_growthpoint_getall },
  "vip_info": { name: "vip_info", route: "/vip/info", category: "VIP中心", module: vip_info },
  "vip_info_v2": { name: "vip_info_v2", route: "/vip/info/v2", category: "VIP中心", module: vip_info_v2 },
  "vip_sign": { name: "vip_sign", route: "/vip/sign", category: "VIP中心", module: vip_sign },
  "vip_sign_detail": { name: "vip_sign_detail", route: "/vip/sign/detail", category: "VIP中心", module: vip_sign_detail },
  "vip_sign_history": { name: "vip_sign_history", route: "/vip/sign/history", category: "VIP中心", module: vip_sign_history },
  "vip_sign_info": { name: "vip_sign_info", route: "/vip/sign/info", category: "VIP中心", module: vip_sign_info },
  "vip_tasks": { name: "vip_tasks", route: "/vip/tasks", category: "VIP中心", module: vip_tasks },
  "vip_tasks_v1": { name: "vip_tasks_v1", route: "/vip/tasks/v1", category: "VIP中心", module: vip_tasks_v1 },
  "vip_timemachine": { name: "vip_timemachine", route: "/vip/timemachine", category: "VIP中心", module: vip_timemachine },
  "voice_delete": { name: "voice_delete", route: "/voice/delete", category: "云盘与声音", module: voice_delete },
  "voice_detail": { name: "voice_detail", route: "/voice/detail", category: "云盘与声音", module: voice_detail },
  "voice_lyric": { name: "voice_lyric", route: "/voice/lyric", category: "云盘与声音", module: voice_lyric },
  "voice_upload": { name: "voice_upload", route: "/voice/upload", category: "云盘与声音", module: voice_upload },
  "voicelist_detail": { name: "voicelist_detail", route: "/voicelist/detail", category: "云盘与声音", module: voicelist_detail },
  "voicelist_list": { name: "voicelist_list", route: "/voicelist/list", category: "云盘与声音", module: voicelist_list },
  "voicelist_list_search": { name: "voicelist_list_search", route: "/voicelist/list/search", category: "云盘与声音", module: voicelist_list_search },
  "voicelist_my_created": { name: "voicelist_my_created", route: "/voicelist/my/created", category: "云盘与声音", module: voicelist_my_created },
  "voicelist_search": { name: "voicelist_search", route: "/voicelist/search", category: "云盘与声音", module: voicelist_search },
  "voicelist_trans": { name: "voicelist_trans", route: "/voicelist/trans", category: "云盘与声音", module: voicelist_trans },
  "weblog": { name: "weblog", route: "/weblog", category: "歌曲", module: weblog },
  "yunbei": { name: "yunbei", route: "/yunbei", category: "云贝", module: yunbei },
  "yunbei_expense": { name: "yunbei_expense", route: "/yunbei/expense", category: "云贝", module: yunbei_expense },
  "yunbei_info": { name: "yunbei_info", route: "/yunbei/info", category: "云贝", module: yunbei_info },
  "yunbei_rcmd_song": { name: "yunbei_rcmd_song", route: "/yunbei/rcmd/song", category: "云贝", module: yunbei_rcmd_song },
  "yunbei_rcmd_song_history": { name: "yunbei_rcmd_song_history", route: "/yunbei/rcmd/song/history", category: "云贝", module: yunbei_rcmd_song_history },
  "yunbei_receipt": { name: "yunbei_receipt", route: "/yunbei/receipt", category: "云贝", module: yunbei_receipt },
  "yunbei_sign": { name: "yunbei_sign", route: "/yunbei/sign", category: "云贝", module: yunbei_sign },
  "yunbei_task_finish": { name: "yunbei_task_finish", route: "/yunbei/task/finish", category: "云贝", module: yunbei_task_finish },
  "yunbei_task_finish_v1": { name: "yunbei_task_finish_v1", route: "/yunbei/task/finish/v1", category: "云贝", module: yunbei_task_finish_v1 },
  "yunbei_task_list_v1": { name: "yunbei_task_list_v1", route: "/yunbei/task/list/v1", category: "云贝", module: yunbei_task_list_v1 },
  "yunbei_task_recommend_song": { name: "yunbei_task_recommend_song", route: "/yunbei/task/recommend/song", category: "云贝", module: yunbei_task_recommend_song },
  "yunbei_tasks": { name: "yunbei_tasks", route: "/yunbei/tasks", category: "云贝", module: yunbei_tasks },
  "yunbei_tasks_todo": { name: "yunbei_tasks_todo", route: "/yunbei/tasks/todo", category: "云贝", module: yunbei_tasks_todo },
  "yunbei_today": { name: "yunbei_today", route: "/yunbei/today", category: "云贝", module: yunbei_today },
};

/** 路由 → 模块名（路径参数解析用） */
export const ROUTES: Record<string, string> = Object.fromEntries(
  Object.values(MODULES).map((e) => [e.route, e.name]),
);

export const MODULE_COUNT = 439;

export function resolveRoute(pathname: string): NcmModuleEntry | undefined {
  return MODULES[ROUTES[pathname]];
}

export function listCategories(): Record<string, NcmModuleEntry[]> {
  const out: Record<string, NcmModuleEntry[]> = {};
  for (const e of Object.values(MODULES)) (out[e.category] ??= []).push(e);
  return out;
}

/** 分类稳定顺序（中文分组展示用） */
export const CATEGORY_ORDER: string[] = [
  "登录与账号", "用户信息", "歌曲", "专辑", "歌手", "歌单", "搜索",
  "推荐与榜单", "私人FM", "MV与视频", "播客与DJ", "广播", "评论",
  "动态与社交", "云盘与声音", "一起听", "VIP中心", "云贝", "音乐人",
  "粉丝中心", "听歌数据", "工具与调试", "其他",
];
